backend:
  name: git-gateway
  repo: bickojima/my-blog
  branch: main

  # OAuth Gateway(あなたのWorker)のURL
  base_url: https://reiwa.casa/oauth

  # /auth に飛ばす
  auth_endpoint: auth


# 画像アップロード先（Astroのpublic配下に置く）
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "ja"

collections:
  - name: "devices"
    label: "Devices"
    folder: "src/content/posts/devices"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "下書き", name: "draft", widget: "boolean", default: false }
      - { label: "概要", name: "summary", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown" }

  - name: "finance"
    label: "Finance"
    folder: "src/content/posts/finance"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "下書き", name: "draft", widget: "boolean", default: false }
      - { label: "概要", name: "summary", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown" }
